version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/youruser/.config/ichiran:/root/.config/ichiran
    environment:
      - PORT=8080 # Match the internal port the app binds to
    networks:
      - ichiran-network

networks:
  ichiran-network:
    driver: bridge