version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PORT=8080
    depends_on:
      - ichiran
    networks:
      - ichiran-network

networks:
  ichiran-network:
    driver: bridge